### ISSUE TITLE
Highlight effect continues even after mouse out

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity-components#107]
Can the highlighter be changed a bit so that the animation stops immediately when the user mouses out? Maybe have the animation stop when the user clicks/taps the button?

**Comment by ivyreese** [comment]
Yes. It was doing that before, but I liked it better with the timeout so I changed it (and I think the timeout works better in some edge cases). I can change it back.

**Comment by ivyreese** [comment]
Ah. I remember why I changed this. If you cease the highlight effect on mouse-out, then users on touchscreen Windows aren't able to use the highlight effect (because of the way Windows handle mouse vs touch events). So, by using the current approach, the highlight effect works reliably across mice, touchscreen Windows, and iOS/Android.

I'm going to leave the effect the way it is for now, but I'll keep this issue open in the hope of figuring out some other way to get this working reliably across all platforms.

**Comment by ivyreese** [comment]
I have somewhat worked around the issues on Windows. It's not great, but it's good enough for now. Thus, the mouse behaviour has been changed to cease the effect on mouseout. I also tested ceasing the effect on click, but that had negative consequences for touch devices, and distinguishing between the two is too tricky at this time.
