### ISSUE TITLE
Hop overs become dashed with the lines

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#110]
This is what I discovered after taking out the hop over from that animation. It was there for a reason I guess. Can this be changed to ignore the hop overs in @dash lines?

**Comment by ivyreese** [comment]
You could make them symbols and give them a specific instance name. Or you could make them a different group than the pilot line group.

**Comment by crystalrubik** [comment]
Yup, I tried group and it didn't work, but making it a symbol did.

_Crystal Rubik_
Designer/Animator
CD Industrial Group Inc.
···································
crystal@cdiginc.com
1-866-628-3224
www.cdiginc.com

**Comment by ivyreese** [comment]
SVGA can't really tell the difference between hop-overs and other lines. Go with the symbol approach for now, and if that's too much of a pain we can revisit this again in the future. Ideally, I'd like to make a dedicated line-drawing tool as part of the v4 upgrade, since a lot of the complexity of schematics comes from the conflict between how lines are so important and how the tools we have for drawing lines (in Flash) are terrible. So if we can hold out till then (next summer?) this issue will just.. go away.
