### ISSUE TITLE
Mixing Pressure, Highlight, Gradients, etc.

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/svg-activity-components#133]
Using the highlight tool over a gradient turns the gradient shape solid white on roll-out.

Example: Check valve with gradient at one end (blue right now, but will take pressure colours from both sides.)
<img width="771" alt="screen shot 2016-09-27 at 10 50 58 am" src="https://cloud.githubusercontent.com/assets/7819612/18883467/8859b556-84a0-11e6-9ffa-db595c4bb0d9.png">

After highlight has been triggered, and removed:
<img width="785" alt="screen shot 2016-09-27 at 10 51 13 am 2" src="https://cloud.githubusercontent.com/assets/7819612/18883511/c286354c-84a0-11e6-8f7e-de7543232018.png">

I don't know if this will ever be a high priority problem; I can design around this issue in the particular case I am working on, and possibly all future cases, too.

**Comment by ivyreese** [comment]
This should be easily fixable.

**Comment by ivyreese** [comment]
This doesn't make sense to me. Highlight has been used on plenty of gradients without issue, AFAIK. Can you provide a reproducible test case?

**Comment by iMcKelvie** [comment]
I've put a copy of the three section valve with this problem in your team folder, where the highlight encompasses the gradient on both pilot choke valves. As soon as you trigger that highlight, by mousing over the choke valve, or by touching the control, you'll see that the gradient disappears, to be replaced by its white square from the drawing.

In this example, I don't actually want to include that gradient in the highlight (a mistake on my part) so the workaround of excluding it by grabbing a deeper symbol is fine for me. In fact, we might never want to do this, but I thought I should note it in case it ever does become a problem.

**Comment by ivyreese** [comment]
Note to future Ivan:

The issue Robyn encountered is the following: Highlight setup happens in `@setup`. The `@radialGradient` was created in `@animate`, applied to a group that contained a placeholder (a path with a white fill). So when the Highlight init happened, the gradient didn't exist yet, so Highlight couldn't catch and cache the gradient fill value. Instead, it saw the white placeholder, and cached that value.

This is technically correct behaviour (the systems are working as designed), but they're interacting in a way that violates reasonable expectations. Similar odd behaviour may occur if mixing `@pressure` with Highlight or dynamic gradients — but any combination of these three should be supported. They should follow precedence rules:
1. On an ancestor-descendent hierarchy: ancestor wins.
2. On one element: highlight wins, then gradients, then pressure.

Point 1 is strange because some interactions are ancestor-wins (eg: Highlight on an ancestor should overrule all coloring applied to children), but others are descendent-wins (lexical scope, fills and strokes in SVG, etc). This might mean that there's a third precedence rule that is more powerful than the above two: some notion of domain-specific priority.

Here's what changes should be made.
1. Short term hack-fix: Delay initializing Highlight until after the first frame of animation. This will allow a gradient created in the animation to be seen by Highlight.
2. Medium term: Encourage the combination of Highlight, Pressure, and Gradients in order to explore how they interact in real-world usage. Targeted hack-fixes may be applied to ease over issues while we explore the space, but they should be commented with a link to this issue.
3. Long term: We need a more formal approach to applying color transformations. For example, we might want a data structure outside the DOM to represent color transformations. For instance, we might want a virtual DOM that offers control over which color transformations have priority. This interacts somewhat with how Flash exports fills and strokes. It might be worth waiting until we're ready to break the expectation that things in SVGA work similarly to how they work in Flash — that is, waiting until we are constructing our scenes in a domain-specific environment.

**Comment by ivyreese** [comment]
Not going to fix. Wait for LunchBox Maker (or whatever we end up calling it).
