### ISSUE TITLE
Buggy Flow Arrows Control Panel Button

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity-components#64]
A few weird things:
1. Arrows button will work in 'schematicMode' before ever hitting `animateMode` first. Otherwise the button won't work after going into `animateMode` first. Edit - there is still a way to get arrows to appear in `schematicMode` after going into `animateMode`, if you interact with the animation before going back into `schematicMode`.
2. They will go out of sync with the arrows button, and on my animation they don't work for the first couple clicks, it's works a bit better on Nathan's animation. (no clue why as they are set up exactly the same as far as we can tell)
3. My arrows are going double the speed as Nathan's arrows are, and mine are even set to go slower than his are in the code. (again, set up exactly the same way, very mysterious, but hopefully not... ;) )

**Comment by crystalrubik** [comment]
More info - This has become an issue since adding the schematic/animate mode to an existing animation, otherwise my arrows button worked as it should before. I had to do an update to an old animation and SVG Activity now requires it to have a schematic/animate button now, so I added it, and found these bugs.

**Comment by crystalrubik** [comment]
We understand why my arrows are going double the speed by what I've done in my code (to try matching Nathan's exactly), what we don't understand is why it's not happening to both of our animations.

**Comment by ivyreese** [comment]
These are all flaws in the way SVGA was designed. I've made some changes to work around some of them.

Here's what you need to change in your animation:
1. Remove the `scope.FlowArrows.start()` call in root.coffee, and remove `scope.root.FlowArrows.start()` in mainstage. As of now, the `FlowArrows.start()` function doesn't do anything. You never need it in your animations again. If you do call it, you'll see a gentle warning in the console.
2. You have `scope.FlowArrows.hide()` in your `scope.schematicMode()` — good. You need to add `scope.FlowArrows.show()` to your `scope.animateMode()`. This is a temporary workaround.

The reason your arrows were going twice as fast was because you were calling `FlowArrows.start()` twice — once in root, once in mainstage. That function was creating an animation loop that animated the arrows. Since you called the `start()` function twice, it created two loops, which meant that it would move the arrows twice per frame, which made them run twice as fast. I've changed it so that you'll see a warning if you somehow create the same animation loop twice. As for why Nathan's wasn't having this problem.. I haven't looked at his code yet. When I do, I'll let you know.

I have not yet fixed the issue with arrows showing up in SchematicMode. That'll require a bit more thought. I'll probably make that happen tomorrow.

**Comment by crystalrubik** [comment]
Thanks! and to sort of answer both versions of your replies: 
1. We didn't code the control panel buttons. And thanks, I will try that out! 
2. I guess we didn't know about `scope.FlowArrows.show()`, we thought that `scope.FlowArrows.start()` was essentially the same thing. 

And yeah, I understood I was telling it to run twice, but when I had removed the `scope.FlowArrows.start()` from one of the sections I had a different problem (which I can't exactly remember at the moment). And yeah, the fact that Nathan's isn't and should be baffled me. ;) 

I'll wait and see if you can figure out the schematicMode issue today then fix it all up.

**Comment by ivyreese** [comment]
See notes in Slack about a temporary workaround. A full and proper fix will require working closely together.
